CREATE TABLE ulice(
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(500),
  zone VARCHAR(100),
  part VARCHAR(500),
  PRIMARY KEY (id)
) ENGINE=INNODB CHARSET=utf8 COLLATE=utf8_general_ci;


INSERT INTO ulice (NAME, zone, part) VALUES ('Březhradská', 'ZONA_A', 'Březhrad');
INSERT INTO ulice (NAME, zone, part) VALUES ('Grégrovo náměstí', 'ZONA_A', 'Březhrad');
INSERT INTO ulice (NAME, zone, part) VALUES ('Jasmínová', 'ZONA_A', 'Březhrad');
INSERT INTO ulice (NAME, zone, part) VALUES ('K Potoku', 'ZONA_A', 'Březhrad');
INSERT INTO ulice (NAME, zone, part) VALUES ('Nový Březhrad', 'ZONA_A', 'Březhrad');
INSERT INTO ulice (NAME, zone, part) VALUES ('Obvodní', 'ZONA_A', 'Březhrad');
INSERT INTO ulice (NAME, zone, part) VALUES ('Poštovní', 'ZONA_A', 'Březhrad');
INSERT INTO ulice (NAME, zone, part) VALUES ('Rovná', 'ZONA_A', 'Březhrad');
INSERT INTO ulice (NAME, zone, part) VALUES ('Šeříková', 'ZONA_A', 'Březhrad');
INSERT INTO ulice (NAME, zone, part) VALUES ('U Hřiště', 'ZONA_A', 'Březhrad');
INSERT INTO ulice (NAME, zone, part) VALUES ('U Lesíka', 'ZONA_A', 'Březhrad');
INSERT INTO ulice (NAME, zone, part) VALUES ('U Náhonu', 'ZONA_A', 'Březhrad');

INSERT INTO ulice (NAME, zone, part) VALUES ('Akademika Heyrovského', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Ambrožova', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Balbínova', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Baťkovo náměstí', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Bidlova', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Bono Publiko', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Botanická', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Bratří Čapků', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Buzulucká', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Collinova', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Čechova', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Čelakovského', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Československé armády', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('ČSA', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Divišova', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Dlouhá', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Eliščino nábřeží', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Franušova', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Gočárova třída', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Havlíčkova', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Heřmanova', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Heyrovského', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Hořická', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Hostivítova', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Hradební', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Chmelova', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Ignáta Herrmanna', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Jana Koziny', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Jarošova', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Jeronýmova', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Jiráskovy sady', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Karla Hynka Máchy', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Karla Tomana', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Kavčí plácek', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Klicperova', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Klumparova', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Komenského', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Kotěrova', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Křižíkova', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Kubištovy sady', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Labská kotlina', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Ladova', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Ludovíta Štúra', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Lužická', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Malé náměstí', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('M. D. Rettigové', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Mánesova', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Masarykovo náměstí', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Mostecká', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Mýtská', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Nábřeží U Přívozu', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Na Hradě', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Na Kotli', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Na Kropáčce', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Nálepkova', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('náměstí Jana Pavla II.', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('náměstí Osvoboditelů', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('náměstí 5.května', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('náměstí Svobody', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Na Střezině', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Nezvalova', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Okružní', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Opletalova', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Orlické nábřeží', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Pajkrova flošna', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Palackého', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Pelclova', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Pilnáčkova', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Pivovarská flošna', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Pivovarské náměstí', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Plácelova', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Pospíšilova', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Průmyslová', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Radoušova', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Rautenkraucova', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Resslova', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Rokycanova', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Rokitanského', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Říční', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Sadovská', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('sady Architekta Lisky', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('sady Vítězsl. Nováka', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('17. listopadu', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Skupova', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Smetanovo nábřeží', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Soukenická', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Srdínkova', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Střelecká', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Šafaříkova', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Šimkova', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Šimkovy sady', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Škroupova', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Špitálská', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Švehlova', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Švendova', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Tomkova', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('třída Karla IV.', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Tylovo nábřeží', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('U Kavalíru', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('U Labe', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Ulrichovo náměstí', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('U Soudu', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Uzavřená', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Úzká', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Velké náměstí', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('V Kopečku', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Vrchlického', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Wonkova', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Zieglerova', 'ZONA_A', 'Centrum');
INSERT INTO ulice (NAME, zone, part) VALUES ('Žižkovy sady', 'ZONA_A', 'Centrum');

INSERT INTO ulice (NAME, zone, part) VALUES ('Anenské náměstí', 'ZONA_A', 'Kukleny');
INSERT INTO ulice (NAME, zone, part) VALUES ('Čejkova cesta', 'ZONA_A', 'Kukleny');
INSERT INTO ulice (NAME, zone, part) VALUES ('Dělnická', 'ZONA_A', 'Kukleny');
INSERT INTO ulice (NAME, zone, part) VALUES ('Denisovo náměstí', 'ZONA_A', 'Kukleny');
INSERT INTO ulice (NAME, zone, part) VALUES ('Gogolova', 'ZONA_A', 'Kukleny');
INSERT INTO ulice (NAME, zone, part) VALUES ('Honkova', 'ZONA_A', 'Kukleny');
INSERT INTO ulice (NAME, zone, part) VALUES ('Jiráskova', 'ZONA_A', 'Kukleny');
INSERT INTO ulice (NAME, zone, part) VALUES ('Kalendova', 'ZONA_A', 'Kukleny');
INSERT INTO ulice (NAME, zone, part) VALUES ('Kampelíkova', 'ZONA_A', 'Kukleny');
INSERT INTO ulice (NAME, zone, part) VALUES ('Koželužská', 'ZONA_A', 'Kukleny');
INSERT INTO ulice (NAME, zone, part) VALUES ('Krunertova', 'ZONA_A', 'Kukleny');
INSERT INTO ulice (NAME, zone, part) VALUES ('Křížkovského', 'ZONA_A', 'Kukleny');
INSERT INTO ulice (NAME, zone, part) VALUES ('Kubištova', 'ZONA_A', 'Kukleny');
INSERT INTO ulice (NAME, zone, part) VALUES ('Kudrnova', 'ZONA_A', 'Kukleny');
INSERT INTO ulice (NAME, zone, part) VALUES ('Ležáky', 'ZONA_A', 'Kukleny');
INSERT INTO ulice (NAME, zone, part) VALUES ('Machovcova', 'ZONA_A', 'Kukleny');
INSERT INTO ulice (NAME, zone, part) VALUES ('Markova', 'ZONA_A', 'Kukleny');
INSERT INTO ulice (NAME, zone, part) VALUES ('náměstí E. F. Buriana', 'ZONA_A', 'Kukleny');
INSERT INTO ulice (NAME, zone, part) VALUES ('Na Stružce', 'ZONA_A', 'Kukleny');
INSERT INTO ulice (NAME, zone, part) VALUES ('Pardubická', 'ZONA_A', 'Kukleny');
INSERT INTO ulice (NAME, zone, part) VALUES ('Pražská třída', 'ZONA_A', 'Kukleny');
INSERT INTO ulice (NAME, zone, part) VALUES ('Růžová', 'ZONA_A', 'Kukleny');
INSERT INTO ulice (NAME, zone, part) VALUES ('Slepá', 'ZONA_A', 'Kukleny');
INSERT INTO ulice (NAME, zone, part) VALUES ('Stěžerská', 'ZONA_A', 'Kukleny');
INSERT INTO ulice (NAME, zone, part) VALUES ('Tomáškova', 'ZONA_A', 'Kukleny');
INSERT INTO ulice (NAME, zone, part) VALUES ('U Svodnice', 'ZONA_A', 'Kukleny');
INSERT INTO ulice (NAME, zone, part) VALUES ('V Domkách', 'ZONA_A', 'Kukleny');
INSERT INTO ulice (NAME, zone, part) VALUES ('Za Škodovkou', 'ZONA_A', 'Kukleny');
INSERT INTO ulice (NAME, zone, part) VALUES ('Zdeňka Wirtha', 'ZONA_A', 'Kukleny');
INSERT INTO ulice (NAME, zone, part) VALUES ('Zelená', 'ZONA_A', 'Kukleny');

INSERT INTO ulice (NAME, zone, part) VALUES ('Adolfa Doležala', 'ZONA_A', 'Malšovice');
INSERT INTO ulice (NAME, zone, part) VALUES ('Cejpova', 'ZONA_A', 'Malšovice');
INSERT INTO ulice (NAME, zone, part) VALUES ('Čajkovského', 'ZONA_A', 'Malšovice');
INSERT INTO ulice (NAME, zone, part) VALUES ('Dubová', 'ZONA_A', 'Malšovice');
INSERT INTO ulice (NAME, zone, part) VALUES ('Emy Destinnové', 'ZONA_A', 'Malšovice');
INSERT INTO ulice (NAME, zone, part) VALUES ('Františka Šubrta', 'ZONA_A', 'Malšovice');
INSERT INTO ulice (NAME, zone, part) VALUES ('Fučíkova', 'ZONA_A', 'Malšovice');
INSERT INTO ulice (NAME, zone, part) VALUES ('Gollova', 'ZONA_A', 'Malšovice');
INSERT INTO ulice (NAME, zone, part) VALUES ('Holubova', 'ZONA_A', 'Malšovice');
INSERT INTO ulice (NAME, zone, part) VALUES ('Hradečnice', 'ZONA_A', 'Malšovice');
INSERT INTO ulice (NAME, zone, part) VALUES ('Jandova', 'ZONA_A', 'Malšovice');
INSERT INTO ulice (NAME, zone, part) VALUES ('Kaštanová', 'ZONA_A', 'Malšovice');
INSERT INTO ulice (NAME, zone, part) VALUES ('Klášterského', 'ZONA_A', 'Malšovice');
INSERT INTO ulice (NAME, zone, part) VALUES ('Kmochova', 'ZONA_A', 'Malšovice');
INSERT INTO ulice (NAME, zone, part) VALUES ('K Osadě', 'ZONA_A', 'Malšovice');
INSERT INTO ulice (NAME, zone, part) VALUES ('Kapitána Fechtnera', 'ZONA_A', 'Malšovice');
INSERT INTO ulice (NAME, zone, part) VALUES ('Krapkova', 'ZONA_A', 'Malšovice');
INSERT INTO ulice (NAME, zone, part) VALUES ('Líznerova', 'ZONA_A', 'Malšovice');
INSERT INTO ulice (NAME, zone, part) VALUES ('Malšovická', 'ZONA_A', 'Malšovice');
INSERT INTO ulice (NAME, zone, part) VALUES ('Miroslava Hájka', 'ZONA_A', 'Malšovice');
INSERT INTO ulice (NAME, zone, part) VALUES ('Miřiovského', 'ZONA_A', 'Malšovice');
INSERT INTO ulice (NAME, zone, part) VALUES ('Mrštíkova', 'ZONA_A', 'Malšovice');
INSERT INTO ulice (NAME, zone, part) VALUES ('Na Brně', 'ZONA_A', 'Malšovice');
INSERT INTO ulice (NAME, zone, part) VALUES ('Na Drahách', 'ZONA_A', 'Malšovice');
INSERT INTO ulice (NAME, zone, part) VALUES ('Náhon', 'ZONA_A', 'Malšovice');
INSERT INTO ulice (NAME, zone, part) VALUES ('Na Hrázce', 'ZONA_A', 'Malšovice');
INSERT INTO ulice (NAME, zone, part) VALUES ('Na Občinách', 'ZONA_A', 'Malšovice');
INSERT INTO ulice (NAME, zone, part) VALUES ('Písečná', 'ZONA_A', 'Malšovice');
INSERT INTO ulice (NAME, zone, part) VALUES ('Přespolní', 'ZONA_A', 'Malšovice');
INSERT INTO ulice (NAME, zone, part) VALUES ('Přímská', 'ZONA_A', 'Malšovice');
INSERT INTO ulice (NAME, zone, part) VALUES ('Růženy Jesenské', 'ZONA_A', 'Malšovice');
INSERT INTO ulice (NAME, zone, part) VALUES ('Rybova', 'ZONA_A', 'Malšovice');
INSERT INTO ulice (NAME, zone, part) VALUES ('Sportovní', 'ZONA_A', 'Malšovice');
INSERT INTO ulice (NAME, zone, part) VALUES ('Sukova', 'ZONA_A', 'Malšovice');
INSERT INTO ulice (NAME, zone, part) VALUES ('Štefcova', 'ZONA_A', 'Malšovice');
INSERT INTO ulice (NAME, zone, part) VALUES ('U Pastvišť', 'ZONA_A', 'Malšovice');
INSERT INTO ulice (NAME, zone, part) VALUES ('U Střelnice', 'ZONA_A', 'Malšovice');
INSERT INTO ulice (NAME, zone, part) VALUES ('Úprkova', 'ZONA_A', 'Malšovice');
INSERT INTO ulice (NAME, zone, part) VALUES ('Vachkova', 'ZONA_A', 'Malšovice');
INSERT INTO ulice (NAME, zone, part) VALUES ('Za Humny', 'ZONA_A', 'Malšovice');
INSERT INTO ulice (NAME, zone, part) VALUES ('Zákrejsova', 'ZONA_A', 'Malšovice');
INSERT INTO ulice (NAME, zone, part) VALUES ('Za Lípou', 'ZONA_A', 'Malšovice');
INSERT INTO ulice (NAME, zone, part) VALUES ('Zámostí', 'ZONA_A', 'Malšovice');

INSERT INTO ulice (NAME, zone, part) VALUES ('Akátová', 'ZONA_A', 'Malšova Lhota');
INSERT INTO ulice (NAME, zone, part) VALUES ('Bělečská', 'ZONA_A', 'Malšova Lhota');
INSERT INTO ulice (NAME, zone, part) VALUES ('Bezová', 'ZONA_A', 'Malšova Lhota');
INSERT INTO ulice (NAME, zone, part) VALUES ('Jalovcová', 'ZONA_A', 'Malšova Lhota');
INSERT INTO ulice (NAME, zone, part) VALUES ('K Břízkám', 'ZONA_A', 'Malšova Lhota');
INSERT INTO ulice (NAME, zone, part) VALUES ('Leknínová', 'ZONA_A', 'Malšova Lhota');
INSERT INTO ulice (NAME, zone, part) VALUES ('Lhotecká', 'ZONA_A', 'Malšova Lhota');
INSERT INTO ulice (NAME, zone, part) VALUES ('Olšová', 'ZONA_A', 'Malšova Lhota');
INSERT INTO ulice (NAME, zone, part) VALUES ('Sadová', 'ZONA_A', 'Malšova Lhota');
INSERT INTO ulice (NAME, zone, part) VALUES ('Trnková', 'ZONA_A', 'Malšova Lhota');
INSERT INTO ulice (NAME, zone, part) VALUES ('Vřesová', 'ZONA_A', 'Malšova Lhota');
INSERT INTO ulice (NAME, zone, part) VALUES ('Brožíkova', 'ZONA_A', 'Moravské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Červeného', 'ZONA_A', 'Moravské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Domečkova', 'ZONA_A', 'Moravské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Durychova', 'ZONA_A', 'Moravské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Exnárova', 'ZONA_A', 'Moravské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Formánkova', 'ZONA_A', 'Moravské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Jana Masaryka', 'ZONA_A', 'Moravské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Kejzlarova', 'ZONA_A', 'Moravské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Kyjovská', 'ZONA_A', 'Moravské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Mandysova', 'ZONA_A', 'Moravské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Na Cvičišti', 'ZONA_A', 'Moravské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Oldřichova', 'ZONA_A', 'Moravské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Palachova', 'ZONA_A', 'Moravské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Prostějovská', 'ZONA_A', 'Moravské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Sekaninova', 'ZONA_A', 'Moravské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Selicharova', 'ZONA_A', 'Moravské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Sezemická', 'ZONA_A', 'Moravské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Souběžná', 'ZONA_A', 'Moravské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Suchého', 'ZONA_A', 'Moravské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Svitavská', 'ZONA_A', 'Moravské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Šantrochova', 'ZONA_A', 'Moravské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Štefánikova', 'ZONA_A', 'Moravské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('třída Edvarda Beneše', 'ZONA_A', 'Moravské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Vysocká', 'ZONA_A', 'Moravské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Antala Staška', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Bendlova', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Boleslavova', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Brněnská', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Buková', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Dobroslavova', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Františka Halase', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Fričova', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Hlavní', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Holická', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Hrdého', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Husova', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Jasanová', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Jedlová', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Jilmová', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('K Aleji', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('K Biřičce', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('K Cikánu', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('K Hvězdárně', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Lesní', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Milady Horákové', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Modřínová', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Moravská', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Mužíkova', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Na Biřičce', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Nad Rozárkou', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Nad Rybníky', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Na Dřevěnce', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Na Konečné', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Na Plachtě', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Národních mučedníků', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Na Rozhraní', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Na Úvoze', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Na Výsluní', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Nemocnice (nová)', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Osiková', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Partyzánská', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Pekařova', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Pešinova', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Pod Vodárnou', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Potoční', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Prašingerova', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Profesora Smotlachy', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Průběžná', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Přemyslova', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Slunečná', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Smrková', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Sokolská', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Střední', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Svatováclavské náměstí', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Šemberova', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Ševčíkova', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Štechova', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Štolbova', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Tovární', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Třebešská', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('U Myslivny', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('U Parku', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Za Jízdárnou', 'ZONA_A', 'Nový Hradec Králové');
INSERT INTO ulice (NAME, zone, part) VALUES ('Za Poštou', 'ZONA_A', 'Nový Hradec Králové');

INSERT INTO ulice (NAME, zone, part) VALUES ('Borovinka', 'ZONA_B', 'Plačice');
INSERT INTO ulice (NAME, zone, part) VALUES ('Kubcova', 'ZONA_B', 'Plačice');
INSERT INTO ulice (NAME, zone, part) VALUES ('Kutnohorská', 'ZONA_B', 'Plačice');
INSERT INTO ulice (NAME, zone, part) VALUES ('Ořechová', 'ZONA_B', 'Plačice');
INSERT INTO ulice (NAME, zone, part) VALUES ('Šumperská', 'ZONA_B', 'Plačice');
INSERT INTO ulice (NAME, zone, part) VALUES ('Vilová', 'ZONA_B', 'Plačice');
INSERT INTO ulice (NAME, zone, part) VALUES ('Vlčkovická', 'ZONA_B', 'Plačice');
INSERT INTO ulice (NAME, zone, part) VALUES ('Cimlerova', 'ZONA_B', 'Plácky');
INSERT INTO ulice (NAME, zone, part) VALUES ('Dědkova', 'ZONA_B', 'Plácky');
INSERT INTO ulice (NAME, zone, part) VALUES ('Jindrova', 'ZONA_B', 'Plácky');
INSERT INTO ulice (NAME, zone, part) VALUES ('Klidná', 'ZONA_B', 'Plácky');
INSERT INTO ulice (NAME, zone, part) VALUES ('Kydlinovská za tratí', 'ZONA_B', 'Plácky');
INSERT INTO ulice (NAME, zone, part) VALUES ('Labská vodárna', 'ZONA_B', 'Plácky');
INSERT INTO ulice (NAME, zone, part) VALUES ('Maxe Malého', 'ZONA_B', 'Plácky');
INSERT INTO ulice (NAME, zone, part) VALUES ('Mlýnská', 'ZONA_B', 'Plácky');
INSERT INTO ulice (NAME, zone, part) VALUES ('Na Valše', 'ZONA_B', 'Plácky');
INSERT INTO ulice (NAME, zone, part) VALUES ('Pobřežní', 'ZONA_B', 'Plácky');
INSERT INTO ulice (NAME, zone, part) VALUES ('Pohlova', 'ZONA_B', 'Plácky');
INSERT INTO ulice (NAME, zone, part) VALUES ('U Fotochemy', 'ZONA_B', 'Plácky');
INSERT INTO ulice (NAME, zone, part) VALUES ('U Kulturního domu', 'ZONA_B', 'Plácky');
INSERT INTO ulice (NAME, zone, part) VALUES ('Voborníkova', 'ZONA_B', 'Plácky');
INSERT INTO ulice (NAME, zone, part) VALUES ('V Tůních', 'ZONA_B', 'Plácky');
INSERT INTO ulice (NAME, zone, part) VALUES ('Bekova', 'ZONA_B', 'Plotiště nad Labem');
INSERT INTO ulice (NAME, zone, part) VALUES ('Bezejmenná', 'ZONA_B', 'Plotiště nad Labem');
INSERT INTO ulice (NAME, zone, part) VALUES ('Hronkova', 'ZONA_B', 'Plotiště nad Labem');
INSERT INTO ulice (NAME, zone, part) VALUES ('Husitská', 'ZONA_B', 'Plotiště nad Labem');
INSERT INTO ulice (NAME, zone, part) VALUES ('Kotrčova', 'ZONA_B', 'Plotiště nad Labem');
INSERT INTO ulice (NAME, zone, part) VALUES ('Koutníkova', 'ZONA_B', 'Plotiště nad Labem');
INSERT INTO ulice (NAME, zone, part) VALUES ('Meruňková', 'ZONA_B', 'Plotiště nad Labem');
INSERT INTO ulice (NAME, zone, part) VALUES ('Mládeže', 'ZONA_B', 'Plotiště nad Labem');
INSERT INTO ulice (NAME, zone, part) VALUES ('Na Důchodě', 'ZONA_B', 'Plotiště nad Labem');
INSERT INTO ulice (NAME, zone, part) VALUES ('Petra Jilemnického', 'ZONA_B', 'Plotiště nad Labem');
INSERT INTO ulice (NAME, zone, part) VALUES ('Plotiště nad Labem', 'ZONA_B', 'Plotiště nad Labem');
INSERT INTO ulice (NAME, zone, part) VALUES ('Předměřická', 'ZONA_B', 'Plotiště nad Labem');
INSERT INTO ulice (NAME, zone, part) VALUES ('Říčařova', 'ZONA_B', 'Plotiště nad Labem');
INSERT INTO ulice (NAME, zone, part) VALUES ('U Dřevony', 'ZONA_B', 'Plotiště nad Labem');
INSERT INTO ulice (NAME, zone, part) VALUES ('U Melounky', 'ZONA_B', 'Plotiště nad Labem');
INSERT INTO ulice (NAME, zone, part) VALUES ('U Náhona', 'ZONA_B', 'Plotiště nad Labem');
INSERT INTO ulice (NAME, zone, part) VALUES ('U Sokola', 'ZONA_B', 'Plotiště nad Labem');
INSERT INTO ulice (NAME, zone, part) VALUES ('Višňová', 'ZONA_B', 'Plotiště nad Labem');

INSERT INTO ulice (NAME, zone, part) VALUES ('Dřevařská', 'ZONA_A', 'Pouchov');
INSERT INTO ulice (NAME, zone, part) VALUES ('Garážní', 'ZONA_A', 'Pouchov');
INSERT INTO ulice (NAME, zone, part) VALUES ('Kyjevská', 'ZONA_A', 'Pouchov');
INSERT INTO ulice (NAME, zone, part) VALUES ('Malá', 'ZONA_A', 'Pouchov');
INSERT INTO ulice (NAME, zone, part) VALUES ('Na Dubech', 'ZONA_A', 'Pouchov');
INSERT INTO ulice (NAME, zone, part) VALUES ('Obchodní', 'ZONA_A', 'Pouchov');
INSERT INTO ulice (NAME, zone, part) VALUES ('Plotišťská', 'ZONA_A', 'Pouchov');
INSERT INTO ulice (NAME, zone, part) VALUES ('Pod Kopcem', 'ZONA_A', 'Pouchov');
INSERT INTO ulice (NAME, zone, part) VALUES ('Rusecká', 'ZONA_A', 'Pouchov');
INSERT INTO ulice (NAME, zone, part) VALUES ('U Kovárny', 'ZONA_A', 'Pouchov');
INSERT INTO ulice (NAME, zone, part) VALUES ('U Letiště', 'ZONA_A', 'Pouchov');
INSERT INTO ulice (NAME, zone, part) VALUES ('U Mostku', 'ZONA_A', 'Pouchov');
INSERT INTO ulice (NAME, zone, part) VALUES ('Vážní', 'ZONA_A', 'Pouchov');
INSERT INTO ulice (NAME, zone, part) VALUES ('Velká', 'ZONA_A', 'Pouchov');
INSERT INTO ulice (NAME, zone, part) VALUES ('Výrobní', 'ZONA_A', 'Pouchov');
INSERT INTO ulice (NAME, zone, part) VALUES ('Zadní', 'ZONA_A', 'Pouchov');
INSERT INTO ulice (NAME, zone, part) VALUES ('Za Kostelem', 'ZONA_A', 'Pouchov');
INSERT INTO ulice (NAME, zone, part) VALUES ('Albertova', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Antonína Dvořáka', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Baarova', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Bezručova', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Blažíčkovo náměstí', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Bohuslava Martinů', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Bozděchova', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Boženy Němcové', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Břetislavova', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Červený Dvůr', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Dobrovského', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Drahoňovského', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Družstevní', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Dukelská třída', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Dykova', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Erbenova', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Farářství', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Fibichova', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Foerstrova', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Fráni Šrámka', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Gebauerova', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Leninova', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Dukelská', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Habrmanova', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Hálkova', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Haškova', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Herbenova', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Horova', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Hrubínova', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Hybešova', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Chelčického', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Ivana Olbrachta', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Jana Krušinky', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Janáčkova', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Jatečný plácek', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Jičínská', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Jiráskovo náměstí', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Jiřího Purkyně', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Jungmannova', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Kampanova', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Karla Čapka', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Karolíny Světlé', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Kollárova', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Kuklenská', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Kydlinovská před tratí', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Letců', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Mařákova', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Medkova', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Mikoláše Alše', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Nádražní', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('náměstí 28.října', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Na Okrouhlíku', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Na Rybárně', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Nerudova', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Odlehlá', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Opatovická', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Oskara Nedbala', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Otokara Březiny', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Pavla Hanuše', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Poděbradova', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Polákova', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Prokopa Holého', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Puškinova', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Raisova', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Rašínova třída', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Riegrovo náměstí', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Rubešova', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Sedláčkova', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Seydlerova', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('S. K. Neumanna', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Sladkovského', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Sokolovská', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Sovova', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Sukovy sady', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Sušilova', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Šmeralova', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Šmilovského', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Trutnovská', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Třebízského', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Turinského', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('U Koruny', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('U Zvoničky', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Václavkova', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Vančurovo náměstí', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Veverkova', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('V Koutech', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('V Lipkách', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Vocelova', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Všehrdova', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Vydrova', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Wintrova', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Wolkerova', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Zamenhofova', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Zeyerova', 'ZONA_A', 'Pražské Předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Želivského', 'ZONA_A', 'Pražské Předměstí');

INSERT INTO ulice (NAME, zone, part) VALUES ('Dolní', 'ZONA_A', 'Roudnička');
INSERT INTO ulice (NAME, zone, part) VALUES ('Do Luh', 'ZONA_A', 'Roudnička');
INSERT INTO ulice (NAME, zone, part) VALUES ('Horní', 'ZONA_A', 'Roudnička');
INSERT INTO ulice (NAME, zone, part) VALUES ('Ke Křížku', 'ZONA_A', 'Roudnička');
INSERT INTO ulice (NAME, zone, part) VALUES ('K Chatám', 'ZONA_A', 'Roudnička');
INSERT INTO ulice (NAME, zone, part) VALUES ('K Polabinám', 'ZONA_A', 'Roudnička');
INSERT INTO ulice (NAME, zone, part) VALUES ('K Rybníku', 'ZONA_A', 'Roudnička');
INSERT INTO ulice (NAME, zone, part) VALUES ('Na Zálesí', 'ZONA_A', 'Roudnička');
INSERT INTO ulice (NAME, zone, part) VALUES ('Pod Lesem', 'ZONA_A', 'Roudnička');
INSERT INTO ulice (NAME, zone, part) VALUES ('Roudničská', 'ZONA_A', 'Roudnička');
INSERT INTO ulice (NAME, zone, part) VALUES ('Ve Svahu', 'ZONA_A', 'Roudnička');
INSERT INTO ulice (NAME, zone, part) VALUES ('Viničná', 'ZONA_A', 'Roudnička');
INSERT INTO ulice (NAME, zone, part) VALUES ('Zalomená', 'ZONA_A', 'Roudnička');
INSERT INTO ulice (NAME, zone, part) VALUES ('Černilovská', 'ZONA_B', 'Rusek');
INSERT INTO ulice (NAME, zone, part) VALUES ('Jaroměřská', 'ZONA_B', 'Rusek');
INSERT INTO ulice (NAME, zone, part) VALUES ('Na Humpolci', 'ZONA_B', 'Rusek');
INSERT INTO ulice (NAME, zone, part) VALUES ('Na Lučinách', 'ZONA_B', 'Rusek');
INSERT INTO ulice (NAME, zone, part) VALUES ('Na Paloukách', 'ZONA_B', 'Rusek');
INSERT INTO ulice (NAME, zone, part) VALUES ('Na Rybníce', 'ZONA_B', 'Rusek');
INSERT INTO ulice (NAME, zone, part) VALUES ('Na Valince', 'ZONA_B', 'Rusek');
INSERT INTO ulice (NAME, zone, part) VALUES ('U Potoka', 'ZONA_B', 'Rusek');
INSERT INTO ulice (NAME, zone, part) VALUES ('Divecká', 'ZONA_B', 'Slatina');
INSERT INTO ulice (NAME, zone, part) VALUES ('K Dehetníku', 'ZONA_B', 'Slatina');
INSERT INTO ulice (NAME, zone, part) VALUES ('Kladská za tratí', 'ZONA_B', 'Slatina');
INSERT INTO ulice (NAME, zone, part) VALUES ('Librantická', 'ZONA_B', 'Slatina');
INSERT INTO ulice (NAME, zone, part) VALUES ('Mokrá', 'ZONA_B', 'Slatina');
INSERT INTO ulice (NAME, zone, part) VALUES ('Na Ohradě', 'ZONA_B', 'Slatina');
INSERT INTO ulice (NAME, zone, part) VALUES ('Obecní', 'ZONA_B', 'Slatina');
INSERT INTO ulice (NAME, zone, part) VALUES ('Piletická', 'ZONA_B', 'Slatina');
INSERT INTO ulice (NAME, zone, part) VALUES ('Svinarská', 'ZONA_B', 'Slatina');
INSERT INTO ulice (NAME, zone, part) VALUES ('Školní', 'ZONA_B', 'Slatina');
INSERT INTO ulice (NAME, zone, part) VALUES ('U Jednoty', 'ZONA_B', 'Slatina');
INSERT INTO ulice (NAME, zone, part) VALUES ('U Koše', 'ZONA_B', 'Slatina');
INSERT INTO ulice (NAME, zone, part) VALUES ('Za Školou', 'ZONA_B', 'Slatina');
INSERT INTO ulice (NAME, zone, part) VALUES ('Bieblova', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Blahoslavova', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Brandlova', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Bratří Štefanů', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Březová', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Gagarinova', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Holečkova', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Jánošíkova', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Javorová', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Ječná', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Jižní', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Kaplířova', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Kladská před tratí', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Kociánovice', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Kovová', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Krátká', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Kubelíkova', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Lidická', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Lipová', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Luční', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Manželů Zemánkových', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Markovice', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Markovická', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Myslbekova', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Myslivečkova', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Na Drážkách', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Na Letné', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Na Mlejnku', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Orebská', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Orlická', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Panelová', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Polní', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Požární', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Severní', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Sládkova', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Slavíčkova', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Slezská', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Stará polní', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Stavební', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Švabinského', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Tichá', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Topolová', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Travní', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Třebechovická', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('třída SNP', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('U Háječku', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Uhelná', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('U Plováren', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('U Trati', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('U Vody', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Vavákova', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Víta Nejedlého', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('V Poli', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Vrázova', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Vrbová', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Zemědělská', 'ZONA_A', 'Slezské předměstí');
INSERT INTO ulice (NAME, zone, part) VALUES ('Borová', 'ZONA_B', 'Svinary');
INSERT INTO ulice (NAME, zone, part) VALUES ('Břidličná', 'ZONA_B', 'Svinary');
INSERT INTO ulice (NAME, zone, part) VALUES ('Citrusová', 'ZONA_B', 'Svinary');
INSERT INTO ulice (NAME, zone, part) VALUES ('Dubinská', 'ZONA_B', 'Svinary');
INSERT INTO ulice (NAME, zone, part) VALUES ('K Borku', 'ZONA_B', 'Svinary');
INSERT INTO ulice (NAME, zone, part) VALUES ('Ke Splavu', 'ZONA_B', 'Svinary');
INSERT INTO ulice (NAME, zone, part) VALUES ('K Lesu', 'ZONA_B', 'Svinary');
INSERT INTO ulice (NAME, zone, part) VALUES ('Květná', 'ZONA_B', 'Svinary');
INSERT INTO ulice (NAME, zone, part) VALUES ('Malinova', 'ZONA_B', 'Svinary');
INSERT INTO ulice (NAME, zone, part) VALUES ('Na Sádkách', 'ZONA_B', 'Svinary');
INSERT INTO ulice (NAME, zone, part) VALUES ('Na Stávku', 'ZONA_B', 'Svinary');
INSERT INTO ulice (NAME, zone, part) VALUES ('Ostrovní', 'ZONA_B', 'Svinary');
INSERT INTO ulice (NAME, zone, part) VALUES ('Ostružinová', 'ZONA_B', 'Svinary');
INSERT INTO ulice (NAME, zone, part) VALUES ('Pod Haltýřem', 'ZONA_B', 'Svinary');
INSERT INTO ulice (NAME, zone, part) VALUES ('Podhůrská', 'ZONA_B', 'Svinary');
INSERT INTO ulice (NAME, zone, part) VALUES ('Slatinská', 'ZONA_B', 'Svinary');
INSERT INTO ulice (NAME, zone, part) VALUES ('Stříbrná', 'ZONA_B', 'Svinary');
INSERT INTO ulice (NAME, zone, part) VALUES ('Šípková', 'ZONA_B', 'Svinary');
INSERT INTO ulice (NAME, zone, part) VALUES ('Točná', 'ZONA_B', 'Svinary');
INSERT INTO ulice (NAME, zone, part) VALUES ('Větrná', 'ZONA_B', 'Svinary');
INSERT INTO ulice (NAME, zone, part) VALUES ('Zahradnická', 'ZONA_B', 'Svinary');

INSERT INTO ulice (NAME, zone, part) VALUES ('Boční', 'ZONA_A', 'Sv. Dvory před Hlavní');
INSERT INTO ulice (NAME, zone, part) VALUES ('Drtinova', 'ZONA_A', 'Sv. Dvory před Hlavní');
INSERT INTO ulice (NAME, zone, part) VALUES ('Dvorská před hlavní', 'ZONA_A', 'Sv. Dvory před Hlavní');
INSERT INTO ulice (NAME, zone, part) VALUES ('Františka Žaloudka', 'ZONA_A', 'Sv. Dvory před Hlavní');
INSERT INTO ulice (NAME, zone, part) VALUES ('Fr. Tichého', 'ZONA_A', 'Sv. Dvory před Hlavní');
INSERT INTO ulice (NAME, zone, part) VALUES ('Jabloňová', 'ZONA_A', 'Sv. Dvory před Hlavní');
INSERT INTO ulice (NAME, zone, part) VALUES ('K Metelce', 'ZONA_A', 'Sv. Dvory před Hlavní');
INSERT INTO ulice (NAME, zone, part) VALUES ('K Meteoru', 'ZONA_A', 'Sv. Dvory před Hlavní');
INSERT INTO ulice (NAME, zone, part) VALUES ('Nová', 'ZONA_A', 'Sv. Dvory před Hlavní');
INSERT INTO ulice (NAME, zone, part) VALUES ('Ovocnářská', 'ZONA_A', 'Sv. Dvory před Hlavní');
INSERT INTO ulice (NAME, zone, part) VALUES ('Pálenecká', 'ZONA_A', 'Sv. Dvory před Hlavní');
INSERT INTO ulice (NAME, zone, part) VALUES ('Třešňová', 'ZONA_A', 'Sv. Dvory před Hlavní');
INSERT INTO ulice (NAME, zone, part) VALUES ('Zahrádkářská', 'ZONA_A', 'Sv. Dvory před Hlavní');
INSERT INTO ulice (NAME, zone, part) VALUES ('Bohdanečská', 'ZONA_B', 'Sv. Dvory za Hlavní');
INSERT INTO ulice (NAME, zone, part) VALUES ('Cihlářská', 'ZONA_B', 'Sv. Dvory za Hlavní');
INSERT INTO ulice (NAME, zone, part) VALUES ('Chaloupky', 'ZONA_B', 'Sv. Dvory za Hlavní');
INSERT INTO ulice (NAME, zone, part) VALUES ('Dvorská za hlavní', 'ZONA_B', 'Sv. Dvory za Hlavní');
INSERT INTO ulice (NAME, zone, part) VALUES ('K Dolíkám', 'ZONA_B', 'Sv. Dvory za Hlavní');
INSERT INTO ulice (NAME, zone, part) VALUES ('Klacovská', 'ZONA_B', 'Sv. Dvory za Hlavní');
INSERT INTO ulice (NAME, zone, part) VALUES ('Postranní', 'ZONA_B', 'Sv. Dvory za Hlavní');
INSERT INTO ulice (NAME, zone, part) VALUES ('Spojovací', 'ZONA_B', 'Sv. Dvory za Hlavní');
INSERT INTO ulice (NAME, zone, part) VALUES ('U Cihelny', 'ZONA_B', 'Sv. Dvory za Hlavní');
INSERT INTO ulice (NAME, zone, part) VALUES ('U Studánky', 'ZONA_B', 'Sv. Dvory za Hlavní');
INSERT INTO ulice (NAME, zone, part) VALUES ('A. Malé', 'ZONA_A', 'Třebeš');
INSERT INTO ulice (NAME, zone, part) VALUES ('Blodkova', 'ZONA_A', 'Třebeš');
INSERT INTO ulice (NAME, zone, part) VALUES ('Hradecká', 'ZONA_A', 'Třebeš');
INSERT INTO ulice (NAME, zone, part) VALUES ('K Labi', 'ZONA_A', 'Třebeš');
INSERT INTO ulice (NAME, zone, part) VALUES ('Křivá', 'ZONA_A', 'Třebeš');
INSERT INTO ulice (NAME, zone, part) VALUES ('Labská louka', 'ZONA_A', 'Třebeš');
INSERT INTO ulice (NAME, zone, part) VALUES ('Machkova', 'ZONA_A', 'Třebeš');
INSERT INTO ulice (NAME, zone, part) VALUES ('Marie Pujmanové', 'ZONA_A', 'Třebeš');
INSERT INTO ulice (NAME, zone, part) VALUES ('M. Majerové', 'ZONA_A', 'Třebeš');
INSERT INTO ulice (NAME, zone, part) VALUES ('Na Břehách', 'ZONA_A', 'Třebeš');
INSERT INTO ulice (NAME, zone, part) VALUES ('Na Jezírkách', 'ZONA_A', 'Třebeš');
INSERT INTO ulice (NAME, zone, part) VALUES ('Na Pískách', 'ZONA_A', 'Třebeš');
INSERT INTO ulice (NAME, zone, part) VALUES ('Na Potoce', 'ZONA_A', 'Třebeš');
INSERT INTO ulice (NAME, zone, part) VALUES ('Okrajová', 'ZONA_A', 'Třebeš');
INSERT INTO ulice (NAME, zone, part) VALUES ('Pod Strání', 'ZONA_A', 'Třebeš');
INSERT INTO ulice (NAME, zone, part) VALUES ('Pod Zámečkem', 'ZONA_A', 'Třebeš');
INSERT INTO ulice (NAME, zone, part) VALUES ('Příčná', 'ZONA_A', 'Třebeš');
INSERT INTO ulice (NAME, zone, part) VALUES ('Rybářská', 'ZONA_A', 'Třebeš');
INSERT INTO ulice (NAME, zone, part) VALUES ('Stříbrná náves', 'ZONA_A', 'Třebeš');
INSERT INTO ulice (NAME, zone, part) VALUES ('Školská', 'ZONA_A', 'Třebeš');
INSERT INTO ulice (NAME, zone, part) VALUES ('Urxova', 'ZONA_A', 'Třebeš');
INSERT INTO ulice (NAME, zone, part) VALUES ('Velehradská', 'ZONA_A', 'Třebeš');
INSERT INTO ulice (NAME, zone, part) VALUES ('Ve Stromovce', 'ZONA_A', 'Třebeš');
INSERT INTO ulice (NAME, zone, part) VALUES ('V Mlejnku', 'ZONA_A', 'Třebeš');
INSERT INTO ulice (NAME, zone, part) VALUES ('Zámeček', 'ZONA_A', 'Třebeš');
INSERT INTO ulice (NAME, zone, part) VALUES ('Zborovská', 'ZONA_A', 'Třebeš');
INSERT INTO ulice (NAME, zone, part) VALUES ('Akademika Bedrny', 'ZONA_A', 'Věkoše');
INSERT INTO ulice (NAME, zone, part) VALUES ('Gruzínská', 'ZONA_A', 'Věkoše');
INSERT INTO ulice (NAME, zone, part) VALUES ('Jana Černého', 'ZONA_A', 'Věkoše');
INSERT INTO ulice (NAME, zone, part) VALUES ('K Sokolovně', 'ZONA_A', 'Věkoše');
INSERT INTO ulice (NAME, zone, part) VALUES ('K Zastávce', 'ZONA_A', 'Věkoše');
INSERT INTO ulice (NAME, zone, part) VALUES ('Lomená', 'ZONA_A', 'Věkoše');
INSERT INTO ulice (NAME, zone, part) VALUES ('Na Barvínku', 'ZONA_A', 'Věkoše');
INSERT INTO ulice (NAME, zone, part) VALUES ('Nad Oborou', 'ZONA_A', 'Věkoše');
INSERT INTO ulice (NAME, zone, part) VALUES ('Na Kopečku', 'ZONA_A', 'Věkoše');
INSERT INTO ulice (NAME, zone, part) VALUES ('Na Zahrádkách', 'ZONA_A', 'Věkoše');
INSERT INTO ulice (NAME, zone, part) VALUES ('Pouchovská', 'ZONA_A', 'Věkoše');
INSERT INTO ulice (NAME, zone, part) VALUES ('Růženy Naskové', 'ZONA_A', 'Věkoše');
INSERT INTO ulice (NAME, zone, part) VALUES ('Smiřická', 'ZONA_A', 'Věkoše');
INSERT INTO ulice (NAME, zone, part) VALUES ('Spořilovská', 'ZONA_A', 'Věkoše');
INSERT INTO ulice (NAME, zone, part) VALUES ('Správčická', 'ZONA_A', 'Věkoše');
INSERT INTO ulice (NAME, zone, part) VALUES ('Široká', 'ZONA_A', 'Věkoše');
INSERT INTO ulice (NAME, zone, part) VALUES ('Truhlářská', 'ZONA_A', 'Věkoše');
INSERT INTO ulice (NAME, zone, part) VALUES ('Věkošská', 'ZONA_A', 'Věkoše');
INSERT INTO ulice (NAME, zone, part) VALUES ('V Lukách', 'ZONA_A', 'Věkoše');
INSERT INTO ulice (NAME, zone, part) VALUES ('Východní', 'ZONA_A', 'Věkoše');
INSERT INTO ulice (NAME, zone, part) VALUES ('Zahradní', 'ZONA_A', 'Věkoše');
INSERT INTO ulice (NAME, zone, part) VALUES ('Za Veterinou', 'ZONA_A', 'Věkoše');
INSERT INTO ulice (NAME, zone, part) VALUES ('Za Zelárnou', 'ZONA_A', 'Věkoše');
INSERT INTO ulice (NAME, zone, part) VALUES ('Žitná', 'ZONA_A', 'Věkoše');